--- 
abstract: Comma-Separated Values manipulation routines
author: 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
build_requires: 
  Config: 0
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.150005
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-CSV_XS
provides: 
  Text::CSV_XS: 
    file: CSV_XS.pm
    version: '1.20'
recommends: 
  Encode: '2.78'
requires: 
  DynaLoader: 0
  IO::Handle: 0
  Test::More: 0
  Tie::Scalar: 0
  perl: '5.006001'
resources: 
  IRC: irc://irc.perl.org/#csv
  homepage: https://metacpan.org/pod/Text::CSV_XS
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Tux/Text-CSV_XS
version: '1.20'
