--- #YAML:1.0
name:               XML-SAX-ExpatXS
version:            1.33
abstract:           Perl SAX 2 XS extension to Expat parser
author:
    - Petr Cimprich <pcimprich AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::SAX:  0.96
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
